version: "3"
services:
  message_bus:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "P@ssw0rd"
    ports:
      - 1433:1433
